version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    env_file: .env
    volumes:
      - .:/app
      - .static:/static
      - .media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: bash -c "python manage.py collectstatic --noinput &&
                      python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    command: bash -c "celery -A config worker -l info"

  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .static:/static
      - .media:/media
    depends_on:
      - web



volumes:
  pgdata:
  static:
  media:
